sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/release-2
    - sudo apt-get update
    - sudo apt-get -y install fish
script:
    - git clone https://github.com/fisherman/fisherman
    - fish -c "fisher i fishery/fishtape; fishtape test/*.fish"
